### ISSUE TITLE
Panic in Kubernetes backend

### ISSUE THREAD

**Issue by caseydavenport** [projectcalico/libcalico-go#331]
```
2017-01-26 01:04:12.636 [PANIC][5429] syncer.go 348: failed to parse annotation: %sunexpected end of JSON input
panic: (*logrus.Entry) (0x16396c0,0xc4204c5e50)

goroutine 23 [running]:
panic(0x16396c0, 0xc4204c5e50)
        /usr/local/go/src/runtime/panic.go:500 +0x1a1
github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.Entry.log(0xc42000e140, 0xc42048bd70, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420276500, ...)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:124 +0x423
github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Entry).Panic(0xc420450730, 0xc4202765d0, 0x1, 0x1)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:169 +0x124
github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Entry).Panicf(0xc420450730, 0x166d07e, 0x2, 0xc4202768a8, 0x1, 0x1)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/entry.go:217 +0x101
github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.(*Logger).Panicf(0xc42000e140, 0x166d07e, 0x2, 0xc4202768a8, 0x1, 0x1)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/logger.go:172 +0x86
github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus.Panicf(0x166d07e, 0x2, 0xc4202768a8, 0x1, 0x1)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/Sirupsen/logrus/exported.go:147 +0x5f
github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).performSnapshot(0xc4204c4230, 0x1, 0xc4205257b8, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:348 +0xc6f
github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).readFromKubernetesAPI(0xc4204c4230)
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:149 +0x199c
created by github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*kubeSyncer).Start
        /go/src/github.com/projectcalico/felix/go/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/syncer.go:66 +0x3f
```

Seen when setting the Namespace annotations to an invalid value with Calico v2.0.1.  Felix then repeatedly crashes.

My Namespace:

```
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    net.beta.kubernetes.io/network-policy: ""
  creationTimestamp: 2017-01-26T00:30:12Z
  name: cali-ns-0
  resourceVersion: "191151"
  selfLink: /api/v1/namespacescali-ns-0
  uid: 999d96a1-e35e-11e6-85e4-42010a8a0138
spec:
  finalizers:
  - kubernetes
status:
  phase: Active
```

Fixing the malformed annotation fixes the crash loop.

**Comment by caseydavenport** [comment]
CC @tomdee I've put this in v2.1.0, but this could be a candidate for a v2.0.2 if we decide to do another bug fix release.
