### ISSUE TITLE
Seg fault applying Node using KDD if BGP section is empty.

### ISSUE THREAD

**Issue by robbrockbank** [projectcalico/libcalico-go#480]
If you apply Node resource configuration with an empty BGP section using KDD backend, we hit a seg fault in libcalico-go.

```
dist/calicoctl-darwin-amd64 apply -f temp-node.yaml 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1dbba6b]

goroutine 1 [running]:
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.mergeCalicoK8sNode(0xc4207b8840, 0xc4200bb600, 0x10, 0x0, 0x0)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node_conversion.go:70 +0x3b
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*nodeClient).Update(0xc42017e630, 0xc4207b8880, 0xc4208432b0, 0x10661b2, 0xc4202d3fc0)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node.go:56 +0x1a5
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*nodeClient).Apply(0xc42017e630, 0xc4207b8880, 0x38, 0x2039c20, 0xc420474000)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/node.go:84 +0x39
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*retryWrapper).Apply(0xc4202ce930, 0xc4207b8880, 0xc420843388, 0x1, 0x1)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/retrywrapper.go:85 +0x64
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s.(*KubeClient).Apply(0xc4201fe2c0, 0xc4207b8880, 0xc420012b90, 0xc4207b8880, 0x0)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/k8s.go:389 +0x69b
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/client.(*Client).apply(0xc4202f8ee0, 0x29b51c0, 0xc420012b90, 0x29c2ec0, 0xc42017e648, 0x1fcc380, 0x1)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/client/client.go:266 +0xb0
github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/client.(*nodes).Apply(0xc42017e648, 0xc4204ee7d0, 0x26c94e27526c0c26, 0x2a26e20, 0x2e1e000)
	/go/src/github.com/projectcalico/calicoctl/vendor/github.com/projectcalico/libcalico-go/lib/client/node.go:74 +0xbf
github.com/projectcalico/calicoctl/calicoctl/resourcemgr.init.4.func1(0xc4202f8ee0, 0x29b51c0, 0xc4201633b0, 0xc42033a1e0, 0x20e6340, 0xc4207716d8, 0x1e48bca)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/resourcemgr/node.go:37 +0x132
github.com/projectcalico/calicoctl/calicoctl/resourcemgr.resourceHelper.Apply(0x211ca75, 0x4, 0x211bbb2, 0x2, 0x29cc180, 0x2030c20, 0xc4203141d0, 0x1, 0x1, 0xc420212980, ...)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/resourcemgr/resourcemgr.go:320 +0x50
github.com/projectcalico/calicoctl/calicoctl/resourcemgr.(*resourceHelper).Apply(0xc42033a1e0, 0xc4202f8ee0, 0x29b51c0, 0xc4201633b0, 0xc420771748, 0x10ff7df, 0xc420771ae8, 0x0)
	<autogenerated>:4 +0xb1
github.com/projectcalico/calicoctl/calicoctl/commands.executeResourceAction(0xc420360c30, 0xc4202f8ee0, 0x29b51c0, 0xc4201633b0, 0x0, 0x0, 0x0, 0x1, 0xc42017e4e0)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/resources.go:287 +0x345
github.com/projectcalico/calicoctl/calicoctl/commands.executeConfigCommand(0xc420360c30, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/resources.go:266 +0x6d4
github.com/projectcalico/calicoctl/calicoctl/commands.Apply(0xc4203fc6c0, 0x3, 0x3)
	/go/src/github.com/projectcalico/calicoctl/calicoctl/commands/apply.go:87 +0xf7
main.main()
	/go/src/github.com/projectcalico/calicoctl/calicoctl/calicoctl.go:80 +0x6d5
```

## Expected Behavior
BGP configuration should be removed from the node.

## Current Behavior
libcalico-go seg faults when applying configuration with an empty BGP section.

## Steps to Reproduce (for bugs)
Spotted using calicoctl.

```
dist/calicoctl-darwin-amd64 apply -f temp-node.yaml 
cat temp-node.yaml 
- apiVersion: v1
  kind: node
  metadata:
    name: rlb-test-kdd-001
  spec:
    bgp:
```

**Comment by heschlie** [comment]
@robbrockbank Just to clarify when we apply with an empty bgp spec we want it to remove all peering related information but  It should still leave the `projectcalico.org/IPv4Address` in place?  

I've fixed the segfault but currently when there is peering or other BGP information annotated on the Node it does not remove it.  Steps I've done to verify:

```bash
calicoctl apply -f peer.yaml
kubectl get no kube-master -o json | jq "."
snip...
"annotations": {
      "node.alpha.kubernetes.io/ttl": "0",
      "peer.bgp.projectcalico.org/aa-bb--ff": "{\"ip\":\"aa:bb::ff\",\"as_num\":\"64514\"}",
      "projectcalico.org/IPv4Address": "10.192.0.2/16",
      "volumes.kubernetes.io/controller-managed-attach-detach": "true"
    },
snip...
calicoctl apply -f empty-bgp.yaml
kubectl get no kube-master -o json | jq "."
snip...
"annotations": {
      "node.alpha.kubernetes.io/ttl": "0",
      "peer.bgp.projectcalico.org/aa-bb--ff": "{\"ip\":\"aa:bb::ff\",\"as_num\":\"64514\"}", # <- still here!
      "projectcalico.org/IPv4Address": "10.192.0.2/16",
      "volumes.kubernetes.io/controller-managed-attach-detach": "true"
    },
snip...
```

peer.yaml
```yaml
apiVersion: v1
kind: bgpPeer
metadata:
  peerIP: aa:bb::ff
  scope: node
  node: kube-master
spec:
  asNumber: 64514
```

empty-bgp.yaml
```yaml
- apiVersion: v1
  kind: node
  metadata:
    name: kube-master
  spec:
    bgp:
```

Just wanted to verify before I sort out why it isn't being removed.

**Comment by robbrockbank** [comment]
It should remove everything I believe - the IPv4 annotation is also part of the BGP spec.
