### ISSUE TITLE
Panic in k8sWatcherConverter

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#624]
Seen in felix's log during a k8sfv test run with `JUST_A_MINUTE=true USE_TYPHA=false make k8sfv-test`

## Expected Behavior
No panics!

## Current Behavior
See this panic about once every 60s in the logs:
```
panic: interface conversion: interface is nil, not resources.Resource

goroutine 102 [running]:
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*k8sWatcherConverter).convertEvent(0xc420114e80, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/watcher.go:118 +0x98
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.(*k8sWatcherConverter).processK8sEvents(0xc420114e80)
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/watcher.go:87 +0x228
created by github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources.newK8sWatcherConverter
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/k8s/resources/watcher.go:43 +0x13d
```
## Your Environment

* libcalico-go version: 80853cf81b74dbde7b6c55dae0d52cfe8e0001c9
* felix version: 0aba6bc56f0a8990795e2ae491a13bd22b0c4683
* Operating System and version: Ubuntu 16.04
* Link to your project (optional):

**Comment by fasaxc** [comment]
Looks like the offending event is a zero struct so `Type = ""`.  Could mean the channel was closed.
