### ISSUE TITLE
Malformed ip pool name causes crash

### ISSUE THREAD

**Issue by fasaxc** [projectcalico/libcalico-go#820]
Seen on Calico 2.6, if you have an IP pool in etcd that has an unexpected name format then we fail to parse it with a panic.

Example key: `/calico/v1/ipam/v4/pool/577559` (taken from an old OpenStack scale testing script).

## Expected Behavior

Warning log and drop.

## Current Behavior

```
panic: invalid CIDR address: 577559

goroutine 71 [running]:
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/model.KeyFromDefaultPath(0xc420321940, 0x1e, 0xc420627b30, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/model/keys.go:209 +0x139c
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd.(*etcdSyncer).sendUpdate(0xc4201a3b60, 0xc420321940, 0x1e, 0xc420042640, 0x3e, 0x124, 0x1)
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd/syncer.go:525 +0xf7
github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd.(*etcdSyncer).mergeUpdates(0xc4201a3b60, 0xc42004f0e0, 0xc42004f080, 0xc42004f140)
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd/syncer.go:456 +0x15d1
created by github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd.(*etcdSyncer).Start
	/go/src/github.com/projectcalico/felix/vendor/github.com/projectcalico/libcalico-go/lib/backend/etcd/syncer.go:158 +0x192
```

## Possible Solution

Handle the error, log and drop instead of panicking.  Audit other key parsing functions for same.

## Steps to Reproduce (for bugs)

1. Manually insert an IP pool with above key
2. Start felix (probably other components affected)
3.
4.

## Your Environment

* libcalico-go version: Something around edcbcf64348004bfeb0dc3882cd2790743ec7728 (using felix from the calico-2.6 PPA)
* Operating System and version: Ubuntu 14.04
* Link to your project (optional):

**Comment by fasaxc** [comment]
Correct.  It was written with an `etcdctl set` in this case.  In the real world, the user could modify etcd directly for purposes unknown or we could hit, for example, a memory corruption on write.

While both of those are rare (at least at 100-node scale?), the impact is that every felix cyclicly restarts.  In the old python felix, we tried very hard to avoid any kind of crash caused by invalid keys or data since they cause cluster-wide outages.  I think "don't panic" should be our motto in the datastore interaction/parsing code.
